app = "fly-io-tj-db-testing"  # Ensure the app name matches the one created on Fly.io

[build]
  dockerfile = "Dockerfile"  # Point to the Dockerfile to build the app

[[services]]
  internal_port = 8080  # Flask's default port
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
  [[services.ports]]
    handlers = ["http"]
    port = 80
