app = "fly-io-tj-db-testing"

[build]
  image = "python:3.9-slim"  # Use a base Python image if you are using Dockerfile

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
  [[services.ports]]
    handlers = ["http"]
    port = 80
