app = "fly-io-tj-db-testing"  # Name should match the app name you selected in the Fly.io interface

[build]
  builder = "heroku/buildpacks:python"  # Use a Python buildpack for Flask apps (no Dockerfile needed)

[[services]]
  internal_port = 8080  # Flask's default port
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
  [[services.ports]]
    handlers = ["http"]
    port = 80
